[options]
Architecture = aarch64
CheckSpace
ParallelDownloads = 5
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Required

[asahi-alarm]
SigLevel = Required DatabaseRequired
Server = https://github.com/asahi-alarm/asahi-alarm/releases/download/aarch64

[core]
Server = https://fl.us.mirror.archlinuxarm.org/aarch64/core

[extra]
Server = https://fl.us.mirror.archlinuxarm.org/aarch64/extra

[alarm]
Server = https://fl.us.mirror.archlinuxarm.org/aarch64/alarm
