#!/usr/bin/env bash
set -Eeuo pipefail
project_root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P); source "$project_root/config/milestones.env"; source "$project_root/scripts/lib/evidence.sh"; tmp=$(mktemp -d "${TMPDIR:-/tmp}/m6-test.XXXXXX"); trap 'rm -rf -- "$tmp"' EXIT
expect_fail() { if "$@" >/dev/null 2>&1; then printf 'unexpected success: %s\n' "$*" >&2; exit 1; fi; }
calibration_hash=$(awk -F '\t' '$1=="J514s" {print $2}' "$project_root/config/milestone6-speaker-calibrations.tsv")
graph_id=$(awk -F '\t' '$1=="J514s" {print $2}' "$project_root/config/milestone6-speaker-dsp-graphs.tsv")
graph_hash=$(awk -F '\t' '$1=="J514s" {print $3}' "$project_root/config/milestone6-speaker-dsp-graphs.tsv")
write_supported_safety() {
    local file=$1 calibration=$2 graph=$3 temperature=$4 active_key=${5:-speakersafetyd_active}
    printf 'check\tvalue\nstatus\tsupported\ncalibration_board\tJ514s\ncalibration_sha256\t%s\n%s\ttrue\ndsp_graph_id\t%s\ndsp_graph_sha256\t%s\namplifier_thermal_telemetry\tdevice=amp;temperature_c=%s\namplifier_thermal_limit\tmax_c=90\nnegative_safety_result\tblocked\n' \
        "$calibration" "$active_key" "$graph_id" "$graph" "$temperature" > "$file"
}
make_input() { local d=$1; mkdir -p "$d"; cp "$project_root/tests/fixtures/m6/valid/identity.txt" "$d/identity.txt"; cp "$project_root/tests/fixtures/kernel/clean.log" "$d/kernel.log"; printf 'test_id\tpath\tmode\twidth\theight\tfps\tstatus\ttelemetry\tevidence\ncamera-1\tcamera\tcapture\t1920\t1080\t30\tobserved\tdevice=T6030;isp=apple-isp;frames=30\ttrace=camera\n' > "$d/camera.tsv"; printf 'test_id\tpath\tdirection\trate\tchannels\tstatus\ttelemetry\tevidence\taction\nmic-1\tmicrophone\tcapture\t48000\t2\tobserved\tdevice=audio;xruns=0\ttrace=mic\tcapture-only\nhead-1\theadphone\tplayback\t48000\t2\tobserved\tdevice=audio;xruns=0\ttrace=headphone\tcapture-of-test-tone\n' > "$d/audio.tsv"; printf 'test_id\tcodec\tdirection\twidth\theight\tstatus\thardware_codec\tsoftware_fallback\ttelemetry\tevidence\thardware_reason\n' > "$d/codecs.tsv"; local c x n=0 hw; for c in h264 hevc vp9; do for x in decode encode; do n=$((n+1)); hw=$([[ $x == decode ]] && printf decoder || printf encoder); printf 'c%d\t%s\t%s\t3840\t2160\tobserved\tT6030-%s-%s\tno\tdevice=T6030;utilization=72%%\ttrace=codec-%d\thardware-codec-selected\n' "$n" "$c" "$x" "$c" "$hw" "$n" >> "$d/codecs.tsv"; done; done; printf 'c-av1\tav1\tdecode\t3840\t2160\tunsupported\tT6030-av1-unsupported\tno\tdevice=T6030;utilization=0%%\ttrace=av1\thardware decoder absent on T6030\nc-prores\tprores\tencode\t3840\t2160\tunsupported\tT6030-prores-unsupported\tno\tdevice=T6030;utilization=0%%\ttrace=prores\thardware encoder support not established\n' >> "$d/codecs.tsv"; cp "$project_root/tests/fixtures/m6/valid/speaker-safety.tsv" "$d/speaker-safety.tsv"; }
valid="$tmp/valid"; make_input "$valid"; out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-test.XXXXXX"); rmdir "$out"; "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$valid" --out "$out" >/dev/null; "$project_root/scripts/verify-m6-media-audio.sh" --bundle "$out" >/dev/null
supported="$tmp/supported"; cp -R "$valid" "$supported"; write_supported_safety "$supported/speaker-safety.tsv" "$calibration_hash" "$graph_hash" 42; supported_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-supported.XXXXXX"); rmdir "$supported_out"; "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$supported" --out "$supported_out" >/dev/null; "$project_root/scripts/verify-m6-media-audio.sh" --bundle "$supported_out" >/dev/null
unapproved_graph="$tmp/unapproved-graph"; cp -R "$supported" "$unapproved_graph"; sed -i.bak 's/^dsp_graph_id\tgraph-j514$/dsp_graph_id\tgraph-unapproved/' "$unapproved_graph/speaker-safety.tsv"; rm -f "$unapproved_graph/speaker-safety.tsv.bak"; unapproved_graph_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-unapproved-graph.XXXXXX"); rmdir "$unapproved_graph_out"; expect_fail "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$unapproved_graph" --out "$unapproved_graph_out"
for binding in speaker_calibration_allowlist_sha256 speaker_dsp_graph_allowlist_sha256; do tampered_bundle="$MILESTONE_EVIDENCE_ROOT/m6-${binding}-tampered.$$"; cp -R -- "$supported_out" "$tampered_bundle"; sed -i.bak "s/^${binding}=.*/${binding}=0000000000000000000000000000000000000000000000000000000000000000/" "$tampered_bundle/manifest.txt"; rm -f -- "$tampered_bundle/manifest.txt.bak"; evidence_write_sums "$tampered_bundle" "$tampered_bundle/SHA256SUMS"; expect_fail "$project_root/scripts/verify-m6-media-audio.sh" --bundle "$tampered_bundle"; done
fallback="$tmp/fallback"; cp -R "$valid" "$fallback"; sed -i.bak '2s/no/cpu/' "$fallback/codecs.tsv"; rm -f "$fallback/codecs.tsv.bak"; fallback_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-fallback.XXXXXX"); rmdir "$fallback_out"; expect_fail "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$fallback" --out "$fallback_out"
speaker="$tmp/speaker"; cp -R "$valid" "$speaker"; sed -i.bak '2s/unsupported/supported/' "$speaker/speaker-safety.tsv"; rm -f "$speaker/speaker-safety.tsv.bak"; speaker_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-speaker.XXXXXX"); rmdir "$speaker_out"; expect_fail "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$speaker" --out "$speaker_out"
for case_name in forged-calibration forged-graph not-speakersafetyd over-limit; do candidate="$tmp/$case_name"; cp -R "$valid" "$candidate"; candidate_calibration=$calibration_hash; candidate_graph=$graph_hash; candidate_temperature=42; active_key=speakersafetyd_active; case $case_name in forged-calibration) candidate_calibration=$(printf '%064d' 9);; forged-graph) candidate_graph=$(printf '%064d' 8);; not-speakersafetyd) active_key=speakersafetyd_status;; over-limit) candidate_temperature=100;; esac; write_supported_safety "$candidate/speaker-safety.tsv" "$candidate_calibration" "$candidate_graph" "$candidate_temperature" "$active_key"; candidate_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-$case_name.XXXXXX"); rmdir "$candidate_out"; expect_fail "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$candidate" --out "$candidate_out"; done
supported_fallback="$tmp/supported-fallback"; cp -R "$valid" "$supported_fallback"; sed -i.bak '2s/no/yes/' "$supported_fallback/codecs.tsv"; rm -f "$supported_fallback/codecs.tsv.bak"; supported_fallback_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-supported-fallback.XXXXXX"); rmdir "$supported_fallback_out"; expect_fail "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$supported_fallback" --out "$supported_fallback_out"
unsupported_fallback="$tmp/unsupported-fallback"; cp -R "$valid" "$unsupported_fallback"; sed -i.bak '8s/no/yes/' "$unsupported_fallback/codecs.tsv"; rm -f "$unsupported_fallback/codecs.tsv.bak"; unsupported_fallback_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-unsupported-fallback.XXXXXX"); rmdir "$unsupported_fallback_out"; expect_fail "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$unsupported_fallback" --out "$unsupported_fallback_out"
software_codec="$tmp/software-codec"; cp -R "$valid" "$software_codec"; sed -i.bak '2s/T6030-h264-decoder/software/' "$software_codec/codecs.tsv"; rm -f "$software_codec/codecs.tsv.bak"; software_codec_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-software-codec.XXXXXX"); rmdir "$software_codec_out"; expect_fail "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$software_codec" --out "$software_codec_out"
zero_camera="$tmp/zero-camera"; cp -R "$valid" "$zero_camera"; sed -i.bak '2s/1920/0/' "$zero_camera/camera.tsv"; rm -f "$zero_camera/camera.tsv.bak"; zero_camera_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-zero-camera.XXXXXX"); rmdir "$zero_camera_out"; expect_fail "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$zero_camera" --out "$zero_camera_out"
virtual_camera="$tmp/virtual-camera"; cp -R "$valid" "$virtual_camera"; sed -i.bak '2s/camera/virtual-camera/' "$virtual_camera/camera.tsv"; rm -f "$virtual_camera/camera.tsv.bak"; virtual_camera_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-virtual-camera.XXXXXX"); rmdir "$virtual_camera_out"; expect_fail "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$virtual_camera" --out "$virtual_camera_out"
malformed_camera="$tmp/malformed-camera"; cp -R "$valid" "$malformed_camera"; sed -i.bak '2s/30/not-a-rate/' "$malformed_camera/camera.tsv"; rm -f "$malformed_camera/camera.tsv.bak"; malformed_camera_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-malformed-camera.XXXXXX"); rmdir "$malformed_camera_out"; expect_fail "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$malformed_camera" --out "$malformed_camera_out"
swapped="$tmp/swapped"; cp -R "$valid" "$swapped"; sed -i.bak 's/microphone\tcapture/microphone\tplayback/' "$swapped/audio.tsv"; rm -f "$swapped/audio.tsv.bak"; swapped_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-swapped.XXXXXX"); rmdir "$swapped_out"; expect_fail "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$swapped" --out "$swapped_out"
printf 'M6-tests=passed\n'
