#!/usr/bin/env bash
set -Eeuo pipefail
project_root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P); source "$project_root/config/milestones.env"
tmp=$(mktemp -d "${TMPDIR:-/tmp}/m5-test.XXXXXX"); trap 'rm -rf -- "$tmp"' EXIT
expect_fail() { if "$@" >/dev/null 2>&1; then printf 'unexpected success: %s\n' "$*" >&2; exit 1; fi; }
make_input() {
    local dir=$1; mkdir -p "$dir"; cp "$project_root/tests/fixtures/m5/valid/identity.txt" "$dir/identity.txt"; cp "$project_root/tests/fixtures/kernel/clean.log" "$dir/kernel.log"; cp "$dir/kernel.log" "$dir/iommu.log"
    printf 'port\tconnector\trequired_orientations\n' > "$dir/inventory.tsv"; local p; for p in magsafe hdmi sdxc headphone; do printf '%s\t%s\tfixed\n' "$p" "$p" >> "$dir/inventory.tsv"; done; for p in usb-c-left-1 usb-c-left-2 usb-c-right-1; do printf '%s\t%s\tnormal,flipped\n' "$p" "$p" >> "$dir/inventory.tsv"; done
    printf 'test_id\tport\torientation\tinterface\toperation\tstatus\ttelemetry\tevidence\n' > "$dir/ports.tsv"; local n=0 o x
    for p in magsafe hdmi sdxc headphone; do n=$((n+1)); printf 'p%03d\t%s\tfixed\tnative\tidentify\tobserved\tdevice=%s;link=up\ttrace=%s\n' "$n" "$p" "$p" "$n" >> "$dir/ports.tsv"; done
    for p in usb-c-left-1 usb-c-left-2 usb-c-right-1; do for o in normal flipped; do for x in usb2-data usb3-data charging usb-pd role-switch dp-alt-mode thunderbolt dock; do n=$((n+1)); printf 'p%03d\t%s\t%s\tusb-c\t%s\tobserved\tdevice=%s;power=stable\ttrace=%s\n' "$n" "$p" "$o" "$x" "$p" "$n" >> "$dir/ports.tsv"; done; done; done
    printf 'test_id\tconnector\tport\torientation\tmode\tadvertised\twidth\theight\tstatus\ttelemetry\tevidence\n' > "$dir/modes.tsv"; for p in usb-c-left-1 usb-c-left-2 usb-c-right-1; do for o in normal flipped; do n=$((n+1)); printf 'mode-%03d\tdp\t%s\t%s\t2560x1440-60\tyes\t2560\t1440\tobserved\tlink=stable;edid=hash-dp-%s-%s\ttrace=dp-mode\n' "$n" "$p" "$o" "$p" "$o" >> "$dir/modes.tsv"; done; done; printf 'mode-hdmi\thdmi\thdmi\tn/a\t3840x2160-60\tyes\t3840\t2160\tobserved\tlink=stable;edid=hash-hdmi\ttrace=hdmi-mode\n' >> "$dir/modes.tsv"
    printf 'test_id\tscenario\tduration_seconds\tstatus\ttelemetry\tevidence\tdevice_class\tport\torientation\tbytes\tsource_sha256\tdestination_sha256\terror_count\tdata_loss\tassociation\n' > "$dir/stress.tsv"; local hash; hash=$(printf '%064d' 1); for x in hotplug unplug-under-load suspend-resume over-current-recovery; do n=$((n+1)); printf 's%03d\t%s\t3600\tobserved\tlink=stable;errors=0\ttrace=%s\tnone\tnone\tfixed\t1\t%s\t%s\t0\tno\tstandalone\n' "$n" "$x" "$x" "$hash" "$hash" >> "$dir/stress.tsv"; done; for p in usb-c-left-1 usb-c-left-2 usb-c-right-1; do for c in storage network; do for o in normal flipped; do n=$((n+1)); printf 's%03d\tthunderbolt-sustained-io\t3600\tobserved\tdevice=%s;errors=0\ttrace=tb-%s-%s-%s\t%s\t%s\t%s\t1048576\t%s\t%s\t0\tno\thotplug,suspend\n' "$n" "$c" "$p" "$c" "$o" "$c" "$p" "$o" "$hash" "$hash" >> "$dir/stress.tsv"; done; done; done
}
valid="$tmp/valid"; make_input "$valid"; out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m5-test.XXXXXX"); rmdir "$out"; "$project_root/scripts/collect-m5-ports.sh" --dry-run --input-dir "$valid" --out "$out" >/dev/null; "$project_root/scripts/verify-m5-ports.sh" --bundle "$out" >/dev/null
missing="$tmp/missing"; cp -R "$valid" "$missing"; sed -i.bak '/usb-c-right-1.*flipped.*usb3-data/d' "$missing/ports.tsv"; rm -f "$missing/ports.tsv.bak"; missing_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m5-missing.XXXXXX"); rmdir "$missing_out"; expect_fail "$project_root/scripts/collect-m5-ports.sh" --dry-run --input-dir "$missing" --out "$missing_out"
bare="$tmp/bare"; cp -R "$valid" "$bare"; sed -i.bak '2s/observed/pass/' "$bare/ports.tsv"; rm -f "$bare/ports.tsv.bak"; bare_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m5-bare.XXXXXX"); rmdir "$bare_out"; expect_fail "$project_root/scripts/collect-m5-ports.sh" --dry-run --input-dir "$bare" --out "$bare_out"
failed_nonusb="$tmp/failed-nonusb"; cp -R "$valid" "$failed_nonusb"; sed -i.bak '2s/observed/failed/' "$failed_nonusb/ports.tsv"; rm -f "$failed_nonusb/ports.tsv.bak"; failed_nonusb_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m5-failed-nonusb.XXXXXX"); rmdir "$failed_nonusb_out"; expect_fail "$project_root/scripts/collect-m5-ports.sh" --dry-run --input-dir "$failed_nonusb" --out "$failed_nonusb_out"
fault="$tmp/fault"; cp -R "$valid" "$fault"; printf 'DART fault\n' >> "$fault/iommu.log"; fault_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m5-fault.XXXXXX"); rmdir "$fault_out"; expect_fail "$project_root/scripts/collect-m5-ports.sh" --dry-run --input-dir "$fault" --out "$fault_out"
missing_op="$tmp/missing-op"; cp -R "$valid" "$missing_op"; sed -i.bak '/usb-c-left-1.*normal.*dp-alt-mode/d' "$missing_op/ports.tsv"; rm -f "$missing_op/ports.tsv.bak"; missing_op_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m5-missing-op.XXXXXX"); rmdir "$missing_op_out"; expect_fail "$project_root/scripts/collect-m5-ports.sh" --dry-run --input-dir "$missing_op" --out "$missing_op_out"
missing_left2="$tmp/missing-left2"; cp -R "$valid" "$missing_left2"; sed -i.bak '/thunderbolt-sustained-io.*storage.*usb-c-left-2/d' "$missing_left2/stress.tsv"; rm -f "$missing_left2/stress.tsv.bak"; missing_left2_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m5-missing-left2.XXXXXX"); rmdir "$missing_left2_out"; expect_fail "$project_root/scripts/collect-m5-ports.sh" --dry-run --input-dir "$missing_left2" --out "$missing_left2_out"
missing_right1="$tmp/missing-right1"; cp -R "$valid" "$missing_right1"; sed -i.bak '/thunderbolt-sustained-io.*network.*usb-c-right-1/d' "$missing_right1/stress.tsv"; rm -f "$missing_right1/stress.tsv.bak"; missing_right1_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m5-missing-right1.XXXXXX"); rmdir "$missing_right1_out"; expect_fail "$project_root/scripts/collect-m5-ports.sh" --dry-run --input-dir "$missing_right1" --out "$missing_right1_out"
opaque="$tmp/opaque"; cp -R "$valid" "$opaque"; sed -i.bak 's/0000000000000000000000000000000000000000000000000000000000000001/integrity-opaque/' "$opaque/stress.tsv"; rm -f "$opaque/stress.tsv.bak"; opaque_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m5-opaque.XXXXXX"); rmdir "$opaque_out"; expect_fail "$project_root/scripts/collect-m5-ports.sh" --dry-run --input-dir "$opaque" --out "$opaque_out"
failed_mode="$tmp/failed-mode"; cp -R "$valid" "$failed_mode"; sed -i.bak '2s/observed/failed/' "$failed_mode/modes.tsv"; rm -f "$failed_mode/modes.tsv.bak"; failed_mode_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m5-failed-mode.XXXXXX"); rmdir "$failed_mode_out"; expect_fail "$project_root/scripts/collect-m5-ports.sh" --dry-run --input-dir "$failed_mode" --out "$failed_mode_out"
mixed_mode="$tmp/mixed-mode"; cp -R "$valid" "$mixed_mode"; printf 'mode-mixed\tdp\tusb-c-left-1\tnormal\t1920x1080-60\tyes\t1920\t1080\tfailed\tlink=failed\ttrace=mixed\n' >> "$mixed_mode/modes.tsv"; mixed_mode_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m5-mixed-mode.XXXXXX"); rmdir "$mixed_mode_out"; expect_fail "$project_root/scripts/collect-m5-ports.sh" --dry-run --input-dir "$mixed_mode" --out "$mixed_mode_out"
data_loss="$tmp/data-loss"; cp -R "$valid" "$data_loss"; sed -i.bak 's/\tno\t/\tyes\t/' "$data_loss/stress.tsv"; rm -f "$data_loss/stress.tsv.bak"; data_loss_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m5-data-loss.XXXXXX"); rmdir "$data_loss_out"; expect_fail "$project_root/scripts/collect-m5-ports.sh" --dry-run --input-dir "$data_loss" --out "$data_loss_out"
mismatched_hash="$tmp/mismatched-hash"; cp -R "$valid" "$mismatched_hash"; sed -i.bak 's/0000000000000000000000000000000000000000000000000000000000000001/0000000000000000000000000000000000000000000000000000000000000002/' "$mismatched_hash/stress.tsv"; rm -f "$mismatched_hash/stress.tsv.bak"; mismatched_hash_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m5-mismatched-hash.XXXXXX"); rmdir "$mismatched_hash_out"; expect_fail "$project_root/scripts/collect-m5-ports.sh" --dry-run --input-dir "$mismatched_hash" --out "$mismatched_hash_out"
printf 'M5-tests=passed\n'
