#!/usr/bin/env bash
set -Eeuo pipefail
project_root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P); source "$project_root/config/milestones.env"; tmp=$(mktemp -d "${TMPDIR:-/tmp}/m7-test.XXXXXX"); trap 'rm -rf -- "$tmp"' EXIT
MILESTONE_EVIDENCE_ROOT="$tmp/evidence"; export MILESTONE_EVIDENCE_ROOT; mkdir -m 700 "$MILESTONE_EVIDENCE_ROOT"
expect_fail() { if "$@" >/dev/null 2>&1; then printf 'unexpected success: %s\n' "$*" >&2; exit 1; fi; }
make_input() {
    local d=$1; mkdir -p "$d"; cp "$project_root/tests/fixtures/m7/valid/identity.txt" "$d/identity.txt"; cp "$project_root/tests/fixtures/kernel/clean.log" "$d/kernel.log"; printf 'key\tvalue\nsip\tenabled\nfilevault\tenabled\nboot_policy\tunchanged\nraw_biometric_export\tfalse\n' > "$d/macos-security.tsv"
    printf 'threat_id\tasset\tboundary\tscenario\tcontrol\tstatus\treviewer\tevidence\ttelemetry\n' > "$d/threat-model.tsv"; local id; for id in sep-boundary touchid-boundary key-isolation pmu ane dma firmware-trust-rollback reset suspend multi-user; do printf '%s\tsecurity-asset\tisolated-boundary\tthreat-%s\tcontrol-reviewed\treviewed\treviewer-1\tevidence-%s\ttrace=%s\n' "$id" "$id" "$id" "$id" >> "$d/threat-model.tsv"; done
    printf 'boundary\tasset\texposed_to\tallowed\tdenied\tstatus\tevidence\textra\n' > "$d/security-boundaries.tsv"; for id in sep touchid key-material pmu ane dma firmware; do printf '%s\tsecurity-asset\ttrusted-kernel\tminimum-interface\tno-export\treviewed\tboundary-evidence-%s\towner=security\n' "$id" "$id" >> "$d/security-boundaries.tsv"; done
    printf 'test_id\taccelerator\tisolation\tfirmware_trust\trollback\treset\tsuspend\tmulti_user\tstatus\ttelemetry\tevidence\n' > "$d/accelerators.tsv"; for id in sep touchid pmu ane; do printf 'a-%s\t%s\tisolated\tverified\treviewed\treviewed\treviewed\treviewed\treviewed\tdevice=%s;state=contained\tevidence-%s\n' "$id" "$id" "$id" "$id" >> "$d/accelerators.tsv"; done
    printf 'test_id\tthreat\taction\texpected\tresult\trecovery_evidence\tstatus\ttelemetry\n' > "$d/negative-tests.tsv"; for id in no-biometric-export no-key-export firmware-rollback dma-boundary reset-recovery suspend-recovery multi-user-isolation; do printf '%s\tsecurity-boundary\tdeny-test\tdenied\tdenied\trecovery-%s\tobserved\ttrace=%s\n' "$id" "$id" "$id" >> "$d/negative-tests.tsv"; done
    printf 'recovery_id\ttrigger\treset_path\tdata_loss\tstatus\tevidence\ttelemetry\textra\nrollback\tfirmware-rollback\ttrusted-rollback\tno\tobserved\trecovery-evidence-rollback\tdevice=sep;state=contained\treviewer=1\nreset\treset\tisolated-reset\tno\tobserved\trecovery-evidence-reset\tdevice=pmu;state=contained\treviewer=1\nsuspend\tsuspend\tresume-check\tno\tobserved\trecovery-evidence-suspend\tdevice=ane;state=contained\treviewer=1\n' > "$d/recovery.tsv"
}
valid="$tmp/valid"; make_input "$valid"; out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m7-test.XXXXXX"); rmdir "$out"; "$project_root/scripts/collect-m7-security.sh" --dry-run --input-dir "$valid" --out "$out" >/dev/null; "$project_root/scripts/verify-m7-security.sh" --bundle "$out" >/dev/null
exposure="$tmp/exposure"; cp -R "$valid" "$exposure"; printf 'exposure\tno raw biometric template export\ttrusted-kernel\tdeny\tblocked\treviewed\tevidence\ttrace\n' >> "$exposure/security-boundaries.tsv"; exposure_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m7-exposure.XXXXXX"); rmdir "$exposure_out"; expect_fail "$project_root/scripts/collect-m7-security.sh" --dry-run --input-dir "$exposure" --out "$exposure_out"
missing="$tmp/missing"; cp -R "$valid" "$missing"; sed -i.bak '/multi-user-isolation/d' "$missing/negative-tests.tsv"; rm -f "$missing/negative-tests.tsv.bak"; missing_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m7-missing.XXXXXX"); rmdir "$missing_out"; expect_fail "$project_root/scripts/collect-m7-security.sh" --dry-run --input-dir "$missing" --out "$missing_out"
security_variant="$tmp/security-variant"; cp -R "$valid" "$security_variant"; sed -i.bak 's/sip\tenabled/sip\tdisabled/' "$security_variant/macos-security.tsv"; rm -f "$security_variant/macos-security.tsv.bak"; security_variant_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m7-security-variant.XXXXXX"); rmdir "$security_variant_out"; expect_fail "$project_root/scripts/collect-m7-security.sh" --dry-run --input-dir "$security_variant" --out "$security_variant_out"
negative_result="$tmp/negative-result"; cp -R "$valid" "$negative_result"; sed -i.bak '2s/denied	denied/denied	allowed/' "$negative_result/negative-tests.tsv"; rm -f "$negative_result/negative-tests.tsv.bak"; negative_result_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m7-negative-result.XXXXXX"); rmdir "$negative_result_out"; expect_fail "$project_root/scripts/collect-m7-security.sh" --dry-run --input-dir "$negative_result" --out "$negative_result_out"
printf 'M7-tests=passed\n'
