#!/usr/bin/env bash
set -Eeuo pipefail
project_root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P); source "$project_root/config/milestones.env"; tmp=$(mktemp -d "${TMPDIR:-/tmp}/m6-test.XXXXXX"); trap 'rm -rf -- "$tmp"' EXIT
expect_fail() { if "$@" >/dev/null 2>&1; then printf 'unexpected success: %s\n' "$*" >&2; exit 1; fi; }
make_input() { local d=$1; mkdir -p "$d"; cp "$project_root/tests/fixtures/m6/valid/identity.txt" "$d/identity.txt"; cp "$project_root/tests/fixtures/kernel/clean.log" "$d/kernel.log"; printf 'test_id\tpath\tmode\twidth\theight\tfps\tstatus\ttelemetry\tevidence\ncamera-1\tcamera\tcapture\t1920\t1080\t30\tobserved\tdevice=T6030;isp=apple-isp;frames=30\ttrace=camera\n' > "$d/camera.tsv"; printf 'test_id\tpath\tdirection\trate\tchannels\tstatus\ttelemetry\tevidence\taction\nmic-1\tmicrophone\tcapture\t48000\t2\tobserved\tdevice=audio;xruns=0\ttrace=mic\tcapture-only\nhead-1\theadphone\tplayback\t48000\t2\tobserved\tdevice=audio;xruns=0\ttrace=headphone\tcapture-of-test-tone\n' > "$d/audio.tsv"; printf 'test_id\tcodec\tdirection\twidth\theight\tstatus\thardware_codec\tsoftware_fallback\ttelemetry\tevidence\thardware_reason\n' > "$d/codecs.tsv"; local c x n=0 hw; for c in h264 hevc vp9; do for x in decode encode; do n=$((n+1)); hw=$([[ $x == decode ]] && printf decoder || printf encoder); printf 'c%d\t%s\t%s\t3840\t2160\tobserved\tT6030-%s-%s\tno\tdevice=T6030;utilization=72%%\ttrace=codec-%d\thardware-codec-selected\n' "$n" "$c" "$x" "$c" "$hw" "$n" >> "$d/codecs.tsv"; done; done; printf 'c-av1\tav1\tdecode\t3840\t2160\tunsupported\tT6030-av1-unsupported\tno\tdevice=T6030;utilization=0%%\ttrace=av1\thardware decoder absent on T6030\nc-prores\tprores\tencode\t3840\t2160\tunsupported\tT6030-prores-unsupported\tno\tdevice=T6030;utilization=0%%\ttrace=prores\thardware encoder support not established\n' >> "$d/codecs.tsv"; cp "$project_root/tests/fixtures/m6/valid/speaker-safety.tsv" "$d/speaker-safety.tsv"; }
valid="$tmp/valid"; make_input "$valid"; out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-test.XXXXXX"); rmdir "$out"; "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$valid" --out "$out" >/dev/null; "$project_root/scripts/verify-m6-media-audio.sh" --bundle "$out" >/dev/null
fallback="$tmp/fallback"; cp -R "$valid" "$fallback"; sed -i.bak '2s/no/cpu/' "$fallback/codecs.tsv"; rm -f "$fallback/codecs.tsv.bak"; fallback_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-fallback.XXXXXX"); rmdir "$fallback_out"; expect_fail "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$fallback" --out "$fallback_out"
speaker="$tmp/speaker"; cp -R "$valid" "$speaker"; sed -i.bak '2s/unsupported/supported/' "$speaker/speaker-safety.tsv"; rm -f "$speaker/speaker-safety.tsv.bak"; speaker_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-speaker.XXXXXX"); rmdir "$speaker_out"; expect_fail "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$speaker" --out "$speaker_out"
for case_name in forged-hash not-speakersafetyd over-limit; do candidate="$tmp/$case_name"; cp -R "$valid" "$candidate"; { printf 'check\tvalue\nstatus\tsupported\ncalibration_board\tJ514s\ncalibration_sha256\t%064d\nspeakersafetyd_active\ttrue\ndsp_graph_id\tgraph-j514\ndsp_graph_sha256\t%064d\namplifier_thermal_telemetry\tdevice=amp;temperature_c=%s\namplifier_thermal_limit\tmax_c=90\nnegative_safety_result\tblocked\n' 9 8 "$([[ $case_name == over-limit ]] && printf 100 || printf 42)"; } > "$candidate/speaker-safety.tsv"; if [[ $case_name == not-speakersafetyd ]]; then sed -i.bak 's/speakersafetyd_active/speakersafetyd_status/' "$candidate/speaker-safety.tsv"; rm -f "$candidate/speaker-safety.tsv.bak"; fi; candidate_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-$case_name.XXXXXX"); rmdir "$candidate_out"; expect_fail "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$candidate" --out "$candidate_out"; done
supported_fallback="$tmp/supported-fallback"; cp -R "$valid" "$supported_fallback"; sed -i.bak '2s/no/yes/' "$supported_fallback/codecs.tsv"; rm -f "$supported_fallback/codecs.tsv.bak"; supported_fallback_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-supported-fallback.XXXXXX"); rmdir "$supported_fallback_out"; expect_fail "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$supported_fallback" --out "$supported_fallback_out"
unsupported_fallback="$tmp/unsupported-fallback"; cp -R "$valid" "$unsupported_fallback"; sed -i.bak '8s/no/yes/' "$unsupported_fallback/codecs.tsv"; rm -f "$unsupported_fallback/codecs.tsv.bak"; unsupported_fallback_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-unsupported-fallback.XXXXXX"); rmdir "$unsupported_fallback_out"; expect_fail "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$unsupported_fallback" --out "$unsupported_fallback_out"
software_codec="$tmp/software-codec"; cp -R "$valid" "$software_codec"; sed -i.bak '2s/T6030-h264-decoder/software/' "$software_codec/codecs.tsv"; rm -f "$software_codec/codecs.tsv.bak"; software_codec_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-software-codec.XXXXXX"); rmdir "$software_codec_out"; expect_fail "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$software_codec" --out "$software_codec_out"
zero_camera="$tmp/zero-camera"; cp -R "$valid" "$zero_camera"; sed -i.bak '2s/1920/0/' "$zero_camera/camera.tsv"; rm -f "$zero_camera/camera.tsv.bak"; zero_camera_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-zero-camera.XXXXXX"); rmdir "$zero_camera_out"; expect_fail "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$zero_camera" --out "$zero_camera_out"
virtual_camera="$tmp/virtual-camera"; cp -R "$valid" "$virtual_camera"; sed -i.bak '2s/camera/virtual-camera/' "$virtual_camera/camera.tsv"; rm -f "$virtual_camera/camera.tsv.bak"; virtual_camera_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-virtual-camera.XXXXXX"); rmdir "$virtual_camera_out"; expect_fail "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$virtual_camera" --out "$virtual_camera_out"
malformed_camera="$tmp/malformed-camera"; cp -R "$valid" "$malformed_camera"; sed -i.bak '2s/30/not-a-rate/' "$malformed_camera/camera.tsv"; rm -f "$malformed_camera/camera.tsv.bak"; malformed_camera_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-malformed-camera.XXXXXX"); rmdir "$malformed_camera_out"; expect_fail "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$malformed_camera" --out "$malformed_camera_out"
swapped="$tmp/swapped"; cp -R "$valid" "$swapped"; sed -i.bak 's/microphone\tcapture/microphone\tplayback/' "$swapped/audio.tsv"; rm -f "$swapped/audio.tsv.bak"; swapped_out=$(mktemp -d "$MILESTONE_EVIDENCE_ROOT/m6-swapped.XXXXXX"); rmdir "$swapped_out"; expect_fail "$project_root/scripts/collect-m6-media-audio.sh" --dry-run --input-dir "$swapped" --out "$swapped_out"
printf 'M6-tests=passed\n'
